repos:
- repo: https://github.com/myint/autoflake
  rev: v2.0.0
  hooks:
  - id: autoflake
    args: ["--in-place"]
    exclude: ^torch_np/tests/numpy_tests/
- repo: https://github.com/timothycrosley/isort
  rev: 5.11.4
  hooks:
  - id: isort
    args: ["--profile", "black", "--filter-files"]
    exclude: ^torch_np/tests/numpy_tests/
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
  - id: black
    exclude: ^torch_np/tests/numpy_tests/
