import torch

from . import _util
from . import _helpers

def deco_binary_ufunc(torch_func):
    """Common infra for binary ufuncs: receive arrays, sort out type casting,
       broadcasting, out array handling etc, and delegate to the
       pytorch function for actual work, then wrap the results into an array.

       x1, x2 are arrays! array_like -> array conversion is the caller responsibility.
    """
    def wrapped(x1, x2, /, out=None, *, where=True,
                casting='same_kind', order='K', dtype=None, subok=False, **kwds):
        _util.subok_not_ok(subok=subok)
        if order != 'K' or not where:
            raise NotImplementedError

        # XXX: dtype=... parameter is silently ignored

        arrays = (x1, x2)
        x1_tensor, x2_tensor = _helpers.cast_and_broadcast(arrays, out, casting)

        result = torch_func(x1_tensor, x2_tensor)

        return _helpers.result_or_out(result, out)
    return wrapped


# the list is autogenerated, cf autogen/gen_ufunc_2.py
add = deco_binary_ufunc(torch.add)
arctan2 = deco_binary_ufunc(torch.arctan2)
bitwise_and = deco_binary_ufunc(torch.bitwise_and)
bitwise_or = deco_binary_ufunc(torch.bitwise_or)
bitwise_xor = deco_binary_ufunc(torch.bitwise_xor)
copysign = deco_binary_ufunc(torch.copysign)
divide = deco_binary_ufunc(torch.divide)
equal = deco_binary_ufunc(torch.eq)
float_power = deco_binary_ufunc(torch.float_power)
floor_divide = deco_binary_ufunc(torch.floor_divide)
fmax = deco_binary_ufunc(torch.fmax)
fmin = deco_binary_ufunc(torch.fmin)
fmod = deco_binary_ufunc(torch.fmod)
gcd = deco_binary_ufunc(torch.gcd)
greater = deco_binary_ufunc(torch.greater)
greater_equal = deco_binary_ufunc(torch.greater_equal)
heaviside = deco_binary_ufunc(torch.heaviside)
hypot = deco_binary_ufunc(torch.hypot)
lcm = deco_binary_ufunc(torch.lcm)
ldexp = deco_binary_ufunc(torch.ldexp)
left_shift = deco_binary_ufunc(torch.bitwise_left_shift)
less = deco_binary_ufunc(torch.less)
less_equal = deco_binary_ufunc(torch.less_equal)
logaddexp = deco_binary_ufunc(torch.logaddexp)
logaddexp2 = deco_binary_ufunc(torch.logaddexp2)
logical_and = deco_binary_ufunc(torch.logical_and)
logical_or = deco_binary_ufunc(torch.logical_or)
logical_xor = deco_binary_ufunc(torch.logical_xor)
matmul = deco_binary_ufunc(torch.matmul)
maximum = deco_binary_ufunc(torch.maximum)
minimum = deco_binary_ufunc(torch.minimum)
remainder = deco_binary_ufunc(torch.remainder)
multiply = deco_binary_ufunc(torch.multiply)
nextafter = deco_binary_ufunc(torch.nextafter)
not_equal = deco_binary_ufunc(torch.not_equal)
power = deco_binary_ufunc(torch.pow)
remainder = deco_binary_ufunc(torch.remainder)
right_shift = deco_binary_ufunc(torch.bitwise_right_shift)
subtract = deco_binary_ufunc(torch.subtract)
divide = deco_binary_ufunc(torch.divide)

